### ISSUE TITLE
bug and temp solution for error: Type 'DocType' does not satisfy the constraint 'Document<any, any, any>'.

### ISSUE THREAD

**Issue by aaronyu6** [francescov1/mongoose-tsgen#75] opened 2021-10-08 14:41 UTC
## mongoose-tsgen: cause error:Type 'DocType' does not satisfy the constraint 'Document<any, any, any>'.

**Brief: this error only occur when generated interface exist. if delete the interface file, problem disappear.**

## error condition 1

mongoose version 6.0.9 latest and an interface file is generated from mtgen. start nestjs

```
npm run start:dev
```

a long error appear

```
node_modules/mongoose/index.d.ts:944:193 - error TS2344: Type 'EnforceDocument<T, TMethods>' does not satisfy the constraint 'Document<any, any, any>'.
  Type 'Require_id<T> | (Document<any, any, T> & Require_id<T> & TMethods)' is not assignable to type 'Document<any, any, any>'.
    Type 'Require_id<T>' is not assignable to type 'Document<any, any, any>'.
      Type '(T & { _id: T["_id"]; }) | (T & { _id: ObjectId; })' is not assignable to type 'Document<any, any, any>'.
        Type 'T & { _id: T["_id"]; }' is not assignable to type 'Document<any, any, any>'.
          The types of '$set(...).replaceOne(...).$where(...).and' are incompatible between these types.
            Type '(array: FilterQuery<Document<any, any, any> & T>[]) => Query<(Document<any, any, any> & T)[], Document<any, any, any> & T, {}, Document<...> & T>' is not assignable to type '(array: FilterQuery<Document<any, any, any>>[]) => Query<Document<any, any, any>[], Document<any, any, any>, {}, Document<any, any, any>>'.
              Types of parameters 'array' and 'array' are incompatible.
                Type 'FilterQuery<Document<any, any, any>>[]' is not assignable to type 'FilterQuery<Document<any, any, any> & T>[]'.
                  Type 'FilterQuery<Document<any, any, any>>' is not assignable to type 'FilterQuery<Document<any, any, any> & T>'.
                    Type 'FilterQuery<Document<any, any, any>>' is not assignable to type '{ [P in keyof (Document<any, any, any> & T)]?: P extends "_id" ? [Extract<(Document<any, any, any> & T)[P], ObjectId>] extends [never] ? Condition<(Document<any, any, any> & T)[P]> : Condition<...> : [...] extends [...] ? Condition<...> : Condition<...>; }'.
                      Type 'Document<any, any, any> & { _id: any; }' is not assignable to type 'Document<any, any, any>'.
                        The types of 'replaceOne(...).$where(...).and' are incompatible between these types.
                          Type '(array: FilterQuery<T>[]) => Query<T[], T, {}, T>' is not assignable to type '(array: FilterQuery<Document<any, any, any>>[]) => Query<Document<any, any, any>[], Document<any, any, any>, {}, Document<any, any, any>>'.
                            Types of parameters 'array' and 'array' are incompatible.
                              Type 'FilterQuery<Document<any, any, any>>[]' is not assignable to type 'FilterQuery<T>[]'.
                                Type 'FilterQuery<Document<any, any, any>>' is not assignable to type 'FilterQuery<T>'.
                                  Type 'FilterQuery<Document<any, any, any>>' is not assignable to type '{ [P in keyof T]?: P extends "_id" ? [Extract<T[P], ObjectId>] extends [never] ? Condition<T[P]> : Condition<string | { _id: ObjectId; } | T[P]> : [...] extends [...] ? Condition<...> : Condition<...>; }'.

944     findByIdAndUpdate(id: mongodb.ObjectId | any, update: UpdateQuery<T>, options: QueryOptions & { rawResult: true }, callback?: (err: CallbackError, doc: any, res: any) => void): Query<any, EnforceDocument<T, TMethods>, T>;
```

## error condition 2

if environment combination changed to: mongoose version **5.13.10** and an interface file is generated.

a single error

- ```
  - error TS2344: Type 'DocType' does not satisfy the constraint 'Document<any, any, any>'.
  
  2113   type QueryWithHelpers<ResultType, DocType, THelpers = {}, RawDocType = DocType> = Query<ResultType, DocType, THelpers, RawDocType> & THelpers;
  ```

if remove the generated interface file, problem disappear, both mongoose latest 5.3.10 and latest 6.0.9 work properly after starting up nestjs with npm run start:dev

## **analysis conclusion:**

The generated interface file is conflicted/incompatible with nestjs normal start up. **it also generate same errors when I run npx typedoc to generate typescript document.**

## Temporary walk around

temporary walk around method is after generation of interface file, copy the needed portion of interface code from interface file to a self-made interface file, and delete auto generated interface file.


system: WSL2 ubuntu 18.04 LTS
my npm ls for recreating problem reference

```
├── @nestjs/cli@7.6.0
├── @nestjs/common@7.6.18
├── @nestjs/core@7.6.18
├── @nestjs/mapped-types@1.0.0
├── @nestjs/platform-express@7.6.18
├── @nestjs/schematics@7.3.1
├── @nestjs/testing@7.6.18
├── @types/express@4.17.13
├── @types/jest@26.0.24
├── @types/mongoose@5.11.97
├── @types/node@14.17.15
├── @types/supertest@2.0.11
├── @typescript-eslint/eslint-plugin@4.31.1
├── @typescript-eslint/parser@4.31.1
├── eslint-config-prettier@8.3.0
├── eslint-plugin-prettier@3.4.1
├── eslint@7.32.0
├── express@4.17.1
├── fs@0.0.1-security
├── jest@26.6.3
├── mongoose-tsgen@8.4.6
├── mongoose@5.13.10
├── prettier@2.4.0
├── reflect-metadata@0.1.13
├── rimraf@3.0.2
├── rxjs@6.6.7
├── supertest@6.1.6
├── ts-jest@26.5.6
├── ts-loader@8.3.0
├── ts-node@10.2.1
├── tsconfig-paths@3.11.0
├── typedoc@0.22.5
└── typescript@4.4.3
```

**Comment by aaronyu6** [comment] 2021-10-08 14:50
/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from 'mongoose';

/**
 * Lean version of CddStatScoreArrDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CddStatDocument.toObject()`.
 * ```
 * const cddstatObject = cddstat.toObject();
 * ```
 */
export type CddStatScoreArr = {
  testCatId: string;
  testCatName: string;
  testCatData: Map<
    string,
    {
      type: {};
      required: {};
    }
  >;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of CddStatDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CddStatDocument.toObject()`. To avoid conflicts with model names, use the type alias `CddStatObject`.
 * ```
 * const cddstatObject = cddstat.toObject();
 * ```
 */
export type CddStat = {
  schemaVer: string;
  cddSn: string;
  cddName: string;
  cddInfo?: Map<string, string>;
  testDate?: Date;
  createdDate?: Date;
  scoreArr: CddStatScoreArr[];
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of CddStatDocument (type alias of `CddStat`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { CddStat } from "../models"
 * import { CddStatObject } from "../interfaces/mongoose.gen.ts"
 *
 * const cddstatObject: CddStatObject = cddstat.toObject();
 * ```
 */
export type CddStatObject = CddStat;

/**
 * Mongoose Query types
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const CddStat = mongoose.model<CddStatDocument, CddStatModel>("CddStat", CddStatSchema);
 * ```
 */
export type CddStatQueries = {};

export type CddStatMethods = {};

export type CddStatStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const CddStat = mongoose.model<CddStatDocument, CddStatModel>("CddStat", CddStatSchema);
 * ```
 */
export type CddStatModel = mongoose.Model<CddStatDocument, CddStatQueries> &
  CddStatStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new CddStat schema instances:
 * ```
 * const CddStatSchema: CddStatSchema = new mongoose.Schema({ ... })
 * ```
 */
export type CddStatSchema = mongoose.Schema<CddStatDocument, CddStatModel>;

/**
 * Mongoose Subdocument type
 *
 * Type of `CddStatDocument["scoreArr"]` element.
 */
export type CddStatScoreArrDocument = mongoose.Types.Subdocument & {
  testCatId: string;
  testCatName: string;
  testCatData: mongoose.Types.Map<{
    type: {};
    required: {};
  }>;
  _id: mongoose.Types.ObjectId;
};

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const CddStat = mongoose.model<CddStatDocument, CddStatModel>("CddStat", CddStatSchema);
 * ```
 */
export type CddStatDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  CddStatQueries
> &
  CddStatMethods & {
    schemaVer: string;
    cddSn: string;
    cddName: string;
    cddInfo?: mongoose.Types.Map<string>;
    testDate?: Date;
    createdDate?: Date;
    scoreArr: mongoose.Types.DocumentArray<CddStatScoreArrDocument>;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Check if a property on a document is populated:
 * ```
 * import { IsPopulated } from "../interfaces/mongoose.gen.ts"
 *
 * if (IsPopulated<UserDocument["bestFriend"]>) { ... }
 * ```
 */
export function IsPopulated<T>(doc: T | mongoose.Types.ObjectId): doc is T {
  return doc instanceof mongoose.Document;
}

/**
 * Helper type used by `PopulatedDocument`. Returns the parent property of a string
 * representing a nested property (i.e. `friend.user` -> `friend`)
 */
type ParentProperty<T> = T extends `${infer P}.${string}` ? P : never;

/**
 * Helper type used by `PopulatedDocument`. Returns the child property of a string
 * representing a nested property (i.e. `friend.user` -> `user`).
 */
type ChildProperty<T> = T extends `${string}.${infer C}` ? C : never;

/**
 * Helper type used by `PopulatedDocument`. Removes the `ObjectId` from the general union type generated
 * for ref documents (i.e. `mongoose.Types.ObjectId | UserDocument` -> `UserDocument`)
 */
type PopulatedProperty<Root, T extends keyof Root> = Omit<Root, T> & {
  [ref in T]: Root[T] extends mongoose.Types.Array<infer U>
    ? mongoose.Types.Array<Exclude<U, mongoose.Types.ObjectId>>
    : Exclude<Root[T], mongoose.Types.ObjectId>;
};

/**
 * Populate properties on a document type:
 * ```
 * import { PopulatedDocument } from "../interfaces/mongoose.gen.ts"
 *
 * function example(user: PopulatedDocument<UserDocument, "bestFriend">) {
 *   console.log(user.bestFriend._id) // typescript knows this is populated
 * }
 * ```
 */
export type PopulatedDocument<DocType, T> = T extends keyof DocType
  ? PopulatedProperty<DocType, T>
  : ParentProperty<T> extends keyof DocType
  ? Omit<DocType, ParentProperty<T>> & {
      [ref in ParentProperty<T>]: DocType[ParentProperty<T>] extends mongoose.Types.Array<
        infer U
      >
        ? mongoose.Types.Array<
            ChildProperty<T> extends keyof U
              ? PopulatedProperty<U, ChildProperty<T>>
              : PopulatedDocument<U, ChildProperty<T>>
          >
        : ChildProperty<T> extends keyof DocType[ParentProperty<T>]
        ? PopulatedProperty<DocType[ParentProperty<T>], ChildProperty<T>>
        : PopulatedDocument<DocType[ParentProperty<T>], ChildProperty<T>>;
    }
  : DocType;

/**
 * Helper types used by the populate overloads
 */
type Unarray<T> = T extends Array<infer U> ? U : T;
type Modify<T, R> = Omit<T, keyof R> & R;

/**
 * Augment mongoose with Query.populate overloads
 */
declare module 'mongoose' {
  interface Query<ResultType, DocType extends Document, THelpers = {}> {
    populate<T extends string>(
      path: T,
      select?: string | any,
      model?: string | Model<any, THelpers>,
      match?: any,
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;

    populate<T extends string>(
      options: Modify<PopulateOptions, { path: T }> | Array<PopulateOptions>,
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;
  }
}

**Comment by francescov1** [comment] 2021-10-12 12:35
Hi @aaronyu6 

I'm sorry I need more information to help out here. If you could create a simple repo to reproduce the issue then I can investigate, but I've never seen such a problem on my end. 

Did uninstalling `@types/mongoose` help at all?

**Comment by joshgachnang** [comment] 2021-11-23 21:00
FWIW, I hit this error running mongoose-tsgen@8.x.x with mongoose@5.13.13. Switching to mongoose-tsgen@7.x.x cleared it up.

**Comment by francescov1** [comment] 2021-11-29 21:03
Thanks for the info! Will investigate further

**Comment by francescov1** [comment] 2021-12-11 21:02
@joshgachnang  are you still seeing this error with the latest version of `mongoose-tsgen`? A few version fixes were included there.

**Comment by joshgachnang** [comment] 2022-01-26 22:51
Whoops, sorry for not responding! I am still seeing this mongoose@6.1.8 and mongoose-tsgen@8.4.8.

**Comment by francescov1** [comment] 2022-01-26 23:32
@joshgachnang  Thanks for the info! Any chance you can provide a simple repro project? Havent had much luck reproducing this.

**Comment by joshgachnang** [comment] 2022-01-27 16:05
Yeah I'll try and figure out a repro. I have another project (newly started, rather than a 6+ year old one) that is using these same versions and doesn't have the issue. So I'm sure it's somewhere in my dependencies or something.

**Comment by dkoo761** [comment] 2022-02-02 18:49
+1

I'm having this same error as well

```
node_modules/mongoose/index.d.ts:2124:103 - error TS2344: Type 'DocType' does not satisfy the constraint 'Document<any, any, any>'.
```

If I comment out the last function in the generated code file (I can't remember the function name but something like "populate" - it's the function that "augments mongoose") when using a single model then the error goes away, so that might help with debugging.

mongo = 5.0.5
mongoose = 6.1.8
mongoose-tsgen = 8.4.8
typescript = 4.5.5
node = 14.18.3

**Comment by francescov1** [comment] 2022-02-02 21:57
Hey @dkoo761 @joshgachnang thanks for all the help here. I believe I've finally hunted down this bug and fixed it [here](https://github.com/francescov1/mongoose-tsgen/pull/83) 🎉 The Mongoose library types are so overcomplicated and constantly changing 😅  

The updates are live in mongoose-tsgen 8.4.10. Can you guys confirm that the issue has been resolved? I was able to repro it in a seemingly random way. so I want to ensure the root problem is fixed before we close this.

**Comment by dkoo761** [comment] 2022-02-02 22:58
@francescov1 Works for me! Thanks so much for the speedy fix! 🤩

**Comment by joshgachnang** [comment] 2022-02-03 14:22
Awesome, thank you!! I'll test out the fix when I'm back in office Tuesday!

**Closed as completed** 2022-02-10 15:59 UTC

**Comment by joshgachnang** [comment] 2022-02-10 22:30
Ah ha, this did work!! Thank you so much!
