### ISSUE TITLE
Using `LeanDocument<...>["_id"]` throws type error

### ISSUE THREAD

**Issue by wootwoot1234** [francescov1/mongoose-tsgen#102] opened 2022-09-09 16:32 UTC
Using `LeanDocument<...>["_id"]` throws type error

This code:
```
            const messageRule = await MessageRule.findById(...).lean();
            const listingID = messageRule.listingID;
            const listingsIDs = await Listing.find({
                $or: [{_id: listingID}, {linkedListingID: listingID}]
            }).distinct("_id");
```
throws this error:
```
No overload matches this call.
  Overload 1 of 3, '(callback?: Callback<ListingDocument[]> | undefined): Query<ListingDocument[], ListingDocument, ListingQueries, ListingDocument>', gave the following error.
    Argument of type '{ $or: ({ _id: string; } | { linkedListingID: string; })[]; }' is not assignable to parameter of type 'Callback<ListingDocument[]>'.
      Object literal may only specify known properties, and '$or' does not exist in type 'Callback<ListingDocument[]>'.ts(2769)
```

but if I cast the `listingID` variable to a non `LeanDocument` it works fine:
```
const listingID = messageRule.listingID as ListingDocument["_id"];
```

It seems like you can't use a `LeanDocument<ListingDocument>["_id"]` in a query but it I'm not sure why.  Is this a bug or am I doing something wrong?

**Comment by francescov1** [comment] 2022-09-12 19:55
@wootwoot1234 Hmm, I dont think the issue is due to using `lean()` here. If you replace `const listingID = messageRule.listingID;` with any string (eg `const listingID = "a string"`) do you get the same error? It seems like the `find` method doesn't like that you are passing an `$or` clause. 

`ListingDocument["_id"]` is usually typed as `any` by mongoose, so the error is likely not showing up because of this. 

What version of Mongoose are you on?

**Comment by francescov1** [comment] 2022-10-21 16:46
@wootwoot1234 Checking in on my last reply, will close this off soon if I dont hear back

**Closed** 2022-11-24 19:50 UTC
